name: GitHub-Profile-3D-Contrib

on:
  # run automatically every 24 hours
  schedule: # 03:00 JST == 18:00 UTC
   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name JamesHa0
          git config user.email 2258693275@qq.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
